name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to AWS
        uses: appleboy/scp-action@master
        with:
          host: 52.58.62.17 
          username: ec2-user
          key: ${{ secrets.AWS_KEY }}
          source: target/my-project.jar
          target: /home/ec2-user/my-project.jar

      - name: Run tests on AWS
        uses: appleboy/ssh-action@master
        with:
          host: 52.58.62.17 
          username: ec2-user
          key: ${{ secrets.AWS_KEY }}
          script: |
            java -jar /home/ec2-user/my-project.jar
